import { motion } from "framer-motion";
import { Scale, AlertTriangle } from "lucide-react";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-slate-50 pt-32 pb-20">
      <div className="container mx-auto px-6 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white rounded-[2.5rem] p-8 md:p-16 shadow-xl shadow-slate-200/50 border border-slate-100"
        >
          <div className="flex items-center gap-4 mb-8">
            <div className="w-14 h-14 rounded-2xl bg-purple-50 flex items-center justify-center text-purple-600">
              <Scale size={30} />
            </div>
            <div>
              <h1 className="text-4xl font-black text-slate-900 tracking-tight">Terms of Service</h1>
              <p className="text-slate-400 font-bold uppercase text-xs tracking-widest mt-1">Last Updated: March 2024</p>
            </div>
          </div>

          <div className="space-y-10 text-slate-600 leading-relaxed font-medium">
            <section className="space-y-4">
              <h2 className="text-2xl font-black text-slate-900">1. Acceptance of Terms</h2>
              <p>
                By accessing or using SkillSense AI, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any part of these terms, you are prohibited from using the platform.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-black text-slate-900">2. Use License</h2>
              <p>
                Permission is granted to temporarily use the platform for personal career enhancement. This is the grant of a license, not a transfer of title. Under this license you may not:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Modify or copy the materials for commercial purposes.</li>
                <li>Attempt to decompile or reverse engineer any software contained on SkillSense AI.</li>
                <li>Remove any copyright or other proprietary notations from the materials.</li>
                <li>Use the AI generation features to generate harmful, illegal, or offensive content.</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-black text-slate-900">3. AI Content Disclaimer</h2>
              <div className="p-6 rounded-2xl bg-amber-50/50 border border-amber-100 flex gap-4">
                <AlertTriangle className="text-amber-500 shrink-0" size={24} />
                <p className="text-sm font-bold text-amber-700 leading-relaxed">
                  Important: Content generated by our AI is meant for guidance and enhancement purposes. SkillSense AI does not guarantee the accuracy or professional results of AI-generated content. Users are responsible for reviewing and verifying all information before use in professional settings.
                </p>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-black text-slate-900">4. Account Responsibility</h2>
              <p>
                You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-black text-slate-900">5. Limitations</h2>
              <p>
                In no event shall SkillSense AI be liable for any damages arising out of the use or inability to use the platform, even if notified orally or in writing of the possibility of such damage.
              </p>
            </section>

            <section className="space-y-4 pt-6 border-t border-slate-100">
              <p className="text-sm font-bold text-slate-400">
                If you have questions regarding these terms, please contact <span className="text-indigo-600">support@skillsense-ai.com</span>.
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default TermsOfService;
